#%RAML 1.0 DataType
properties:
  firstName:
    type: string  
    example: "Ulrich"
  lastName:
    type: string
    example: "Nielsen"
  companyName:
    type: string
    example: "E-ffoc"
  email:
    type: string
    example:  "ulrichN@effoc.com"
  phone:
    type: string
    example: "+494341927420"
      
  
          
        

          
      

  
      
      